# Generated by Django 4.0.2 on 2022-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='main/profile_img/avatar.png', null=True, upload_to='main/profile_img', verbose_name='Фотография'),
        ),
    ]
