# Generated by Django 4.0.2 on 2022-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_slug_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
