# Generated by Django 4.0.2 on 2022-03-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
